services:
  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    environment:
      INFISICAL_DOMAIN: ${INFISICAL_DOMAIN}
      INFISICAL_TOKEN: ${INFISICAL_TOKEN}
      INFISICAL_PROJECT_ID: ${INFISICAL_PROJECT_ID}
      INFISICAL_ENV: ${INFISICAL_ENV:-production}
      REDIS_URL: ${REDIS_URL}
    restart: unless-stopped

  client:
    build:
      context: .
      dockerfile: apps/client/Dockerfile
      args:
        VITE_SERVER_URL: ${VITE_SERVER_URL}
    restart: unless-stopped
    ports:
      - 6753:80
