/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GameLinksRouteImport } from './routes/game-links'
import { Route as CreateGameRouteImport } from './routes/create-game'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VoteGameIdIndexRouteImport } from './routes/vote_/$gameId/index'
import { Route as LobbyLobbyIdIndexRouteImport } from './routes/lobby_/$lobbyId/index'
import { Route as LobbyLobbyIdControlRouteImport } from './routes/lobby_/$lobbyId/control'

const GameLinksRoute = GameLinksRouteImport.update({
  id: '/game-links',
  path: '/game-links',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateGameRoute = CreateGameRouteImport.update({
  id: '/create-game',
  path: '/create-game',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VoteGameIdIndexRoute = VoteGameIdIndexRouteImport.update({
  id: '/vote_/$gameId/',
  path: '/vote/$gameId/',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyLobbyIdIndexRoute = LobbyLobbyIdIndexRouteImport.update({
  id: '/lobby_/$lobbyId/',
  path: '/lobby/$lobbyId/',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyLobbyIdControlRoute = LobbyLobbyIdControlRouteImport.update({
  id: '/lobby_/$lobbyId/control',
  path: '/lobby/$lobbyId/control',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-game': typeof CreateGameRoute
  '/game-links': typeof GameLinksRoute
  '/lobby/$lobbyId/control': typeof LobbyLobbyIdControlRoute
  '/lobby/$lobbyId/': typeof LobbyLobbyIdIndexRoute
  '/vote/$gameId/': typeof VoteGameIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-game': typeof CreateGameRoute
  '/game-links': typeof GameLinksRoute
  '/lobby/$lobbyId/control': typeof LobbyLobbyIdControlRoute
  '/lobby/$lobbyId': typeof LobbyLobbyIdIndexRoute
  '/vote/$gameId': typeof VoteGameIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-game': typeof CreateGameRoute
  '/game-links': typeof GameLinksRoute
  '/lobby_/$lobbyId/control': typeof LobbyLobbyIdControlRoute
  '/lobby_/$lobbyId/': typeof LobbyLobbyIdIndexRoute
  '/vote_/$gameId/': typeof VoteGameIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-game'
    | '/game-links'
    | '/lobby/$lobbyId/control'
    | '/lobby/$lobbyId/'
    | '/vote/$gameId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-game'
    | '/game-links'
    | '/lobby/$lobbyId/control'
    | '/lobby/$lobbyId'
    | '/vote/$gameId'
  id:
    | '__root__'
    | '/'
    | '/create-game'
    | '/game-links'
    | '/lobby_/$lobbyId/control'
    | '/lobby_/$lobbyId/'
    | '/vote_/$gameId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateGameRoute: typeof CreateGameRoute
  GameLinksRoute: typeof GameLinksRoute
  LobbyLobbyIdControlRoute: typeof LobbyLobbyIdControlRoute
  LobbyLobbyIdIndexRoute: typeof LobbyLobbyIdIndexRoute
  VoteGameIdIndexRoute: typeof VoteGameIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/game-links': {
      id: '/game-links'
      path: '/game-links'
      fullPath: '/game-links'
      preLoaderRoute: typeof GameLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-game': {
      id: '/create-game'
      path: '/create-game'
      fullPath: '/create-game'
      preLoaderRoute: typeof CreateGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vote_/$gameId/': {
      id: '/vote_/$gameId/'
      path: '/vote/$gameId'
      fullPath: '/vote/$gameId/'
      preLoaderRoute: typeof VoteGameIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby_/$lobbyId/': {
      id: '/lobby_/$lobbyId/'
      path: '/lobby/$lobbyId'
      fullPath: '/lobby/$lobbyId/'
      preLoaderRoute: typeof LobbyLobbyIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby_/$lobbyId/control': {
      id: '/lobby_/$lobbyId/control'
      path: '/lobby/$lobbyId/control'
      fullPath: '/lobby/$lobbyId/control'
      preLoaderRoute: typeof LobbyLobbyIdControlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateGameRoute: CreateGameRoute,
  GameLinksRoute: GameLinksRoute,
  LobbyLobbyIdControlRoute: LobbyLobbyIdControlRoute,
  LobbyLobbyIdIndexRoute: LobbyLobbyIdIndexRoute,
  VoteGameIdIndexRoute: VoteGameIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
